services:
  postgres:
    image: postgres:15
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      retries: 5

  airflow-init:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: airflow-init
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      OPENWEATHER_API_KEY: "${OPENWEATHER_API_KEY:-}"
    entrypoint: ["/opt/airflow/init_airflow.sh"]
    restart: "no"

  airflow-webserver:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: airflow-webserver
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__SECRET_KEY: "mysecretkey123"
      OPENWEATHER_API_KEY: "${OPENWEATHER_API_KEY:-}"
    command: webserver
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
      - ./tests:/opt/airflow/tests
      - ./data:/opt/airflow/data
      - ./config:/opt/airflow/config
      - ./output:/opt/airflow/output
    user: "${AIRFLOW_UID}:${AIRFLOW_GID}"
    restart: always

  airflow-scheduler:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: airflow-scheduler
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__SECRET_KEY: "mysecretkey123"
      OPENWEATHER_API_KEY: "${OPENWEATHER_API_KEY:-}"
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
      - ./tests:/opt/airflow/tests
      - ./data:/opt/airflow/data
      - ./config:/opt/airflow/config
      - ./output:/opt/airflow/output
    user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}"
    restart: always

volumes:
  postgres_db: