# Default .env location
ENV_FILE=.env

# Command: make up
up: check-env setup-dirs build init
	@echo "🚀 Starting Airflow stack with .env configuration..."
	docker compose up -d

# Command: make down
down:
	@echo "🛑 Stopping Airflow stack..."
	docker compose down

# Command: make restart
restart: down up

# Command: make logs
logs:
	docker compose logs -f

# Command: make test
test:
	@echo "🧪 Running pytest data quality checks..."
	docker compose exec airflow-worker pytest tests/

# Build Airflow images
build:
	@echo "🔨 Building Airflow images..."
	docker compose build

# Initialize Airflow
init:
	@echo "⚙️ Checking if Airflow DB is already initialized..."
	@if docker compose exec -T postgres psql -U airflow -d airflow -c '\dt' >/dev/null 2>&1; then \
		echo "✅ Airflow DB already initialized, skipping init."; \
	else \
		echo "🔧 Initializing Airflow database and users..."; \
		docker compose run --rm airflow-init; \
	fi

# Ensure required folders exist with correct ownership
setup-dirs:
	@echo "📂 Creating and fixing permissions for data/ and output/..."
	mkdir -p data output
	@if [ "$$(uname)" != "Linux" ]; then \
	  echo "⚠️ Skipping chown (not needed on Windows/macOS)"; \
	else \
	  sudo chown -R 50000:0 data output; \
	fi

# Ensure .env exists
check-env:
	@if [ ! -f $(ENV_FILE) ]; then \
		echo "⚙️  .env not found, creating one..."; \
		read -p 'Enter your OpenWeather API key: ' APIKEY; \
		echo "AIRFLOW_UID=50000" > $(ENV_FILE); \
		echo "AIRFLOW_GID=0" >> $(ENV_FILE); \
		echo "OPENWEATHER_API_KEY=$$APIKEY" >> $(ENV_FILE); \
		echo ".env file created ✅"; \
	else \
		echo "✅ Using existing .env"; \
	fi