version: '3.8'

x-airflow-env: &airflow-env
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__WEBSERVER__RBAC: "True"
  # Optional: pass OWM key via Airflow Variable or env
  OWM_API_KEY: ${OWM_API_KEY:-}

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      <<: *airflow-env
    volumes:
      - ../dags:/opt/airflow/dags
      - ../etl:/opt/airflow/etl
      - ../data:/opt/airflow/data
    ports:
      - "8080:8080"
    entrypoint: /bin/bash
    command:
      - -c
      - |
        /opt/airflow/init_airflow.sh && \
        exec airflow webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      <<: *airflow-env
    volumes:
      - ../dags:/opt/airflow/dags
      - ../etl:/opt/airflow/etl
      - ../data:/opt/airflow/data
    command: ["scheduler"]

volumes:
  postgres-db-volume: